### Obtener todos los productos
GET http://localhost:3000/products
Authorization: Bearer {{token}}

###

### Obtener un producto por ID
GET http://localhost:3000/products/1
Authorization: Bearer {{token}}

###

### Crear un nuevo producto
POST http://localhost:3000/products/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Tarta tres leches",
    "price": 4.40,
    "category": "Vainilla"
}

###

### Actualizar un producto existente
PUT http://localhost:3000/products/add/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Maiz tarta ",
  "price": 11.99,
  "category": "Maiz"
}

###

### Eliminar un producto
DELETE http://localhost:3000/products/3
Authorization: Bearer {{token}}
